### ISSUE TITLE
Enable the ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS in the docker installaton

### ISSUE THREAD

**Issue by GiulioRomualdi** [Giulero/robotology_docker#1]
Hi @Giulero, thank you for the effort! It would be nice to  enable `ROBOTOLOGY_ENABLE_DYNAMICS_FULL_DEPS` option in the superbiuld installation

**Comment by Giulero** [comment]
Done in 773d471! ;)

**Comment by GiulioRomualdi** [comment]
Thank you!
